services:
  portfolio:
    build: .
    container_name: portfolio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`lenny-dev.de`, `www.lenny-dev.de`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true